### ISSUE TITLE
Feature test server

### ISSUE THREAD

**Issue by sonirico** [fernando24164/proxy_scraper#2]
To my knowledge, go structs cannot be monckey-patched, so cant be `net/http` package. It would be ideal to set up http servers mocking responses on the fly.

**Comment by fernando24164** [comment]
There is a mock HTTPCommandMock to test this kind of commands.

```
//Added to make a mock Command
type CommandTest interface {
	Execute() *html.Node
}

type HTTPCommandMock struct {
	isCached bool
}

func (hcm *HTTPCommandMock) Execute() *html.Node {
	hcm.isCached = true
	return &html.Node{}
}
```
